### ISSUE TITLE
Why not just bake this logic into the EKS resource itself

### ISSUE THREAD

**Issue by clayvan** [aws-quickstart/quickstart-amazon-eks-cluster-resource-provider#1]
Hey @jaymccon, first off thank you for all the work you do on the EKS QS repo.

My big question is, why not just bake this logic for private endpoint and logging into the EKS resource itself? Why did you have to create a workaround to do this?

It seems like you just did all the work that the [EKS::Cluster](https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html) resource should be doing behind the scenes.

Is there a reason this logic couldn't be added into that resource? Is it just a matter of testing this logic before CF adopts it? Is it a political issue because it's 2 different teams?

FYI the CF issue for reference: https://github.com/aws/containers-roadmap/issues/242
edit: and the CF roadmap issue: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/118

**Comment by jaymccon** [comment]
The primary purpose of this resource is to add functionality required by the Quick Start, which is likely beyond the scope of what the AWS::EKS::Cluster would or should be handling. With the release of the CloudFormation registry I foresee this pattern of community resource types providing more prescriptive/targeted implementations of native resource types becoming more common.

**Comment by clayvan** [comment]
Seems reasonable enough.

I think for the 2 specific features I mentioned (logging and private endpoint), those seem like obvious EKS::Cluster features.

However I would agree that the rest of the features of this resource provider would be outside the scope of the EKS::Cluster resource. I'll go ahead and close this in hopes that the features mentioned are coming soon for the CloudFormation team. Thanks
